---
version: '3.8'

services:
  powerdns:
    image: powerdns/pdns-auth-48:latest
    ports:
      - "8053:53"
      - "8053:53/udp"
      - "8080:80"
    volumes:
      - ./scripts/init_docker_fixtures.sh:/init_docker_fixtures.sh:ro
    restart: always
    command: [
      "--webserver=yes",
      "--webserver-address=0.0.0.0",
      "--webserver-port=80",
      "--webserver-password=webserverpw",
      "--webserver-allow-from=0.0.0.0/0",
      "--api=yes",
      "--api-key=apipw",
      "--disable-syslog=yes",
      "--loglevel=9",
      "--log-dns-queries=yes",
      "--log-dns-details=yes",
      "--query-logging=yes",
      "--default-soa-edit=INCEPTION-INCREMENT"
    ]
