---
name: govulncheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "21 7 * * 5"
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  govulncheck:
    runs-on: ubuntu-slim
    steps:
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1
        with:
          go-version-input: "1.26"
          go-package: ./...
          check-latest: true
