---
name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          check-latest: true
      - run: |
          gofmt -d .
          test -z $(gofmt -l .)
