---
name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
jobs:
  test-with-mocks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.22"
          - "1.23"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - run: go test -v -coverprofile="coverage.out" ./...
      - run: go tool cover -func="coverage.out"
      - uses: vladopajic/go-test-coverage@v2.11.3
        with:
          config: ".github/testcoverage.yml"
  test-without-mocks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.22"
          - "1.23"
        pdns-auth-image:
          - powerdns/pdns-auth-47:latest
          - powerdns/pdns-auth-48:latest
          - powerdns/pdns-auth-49:latest
    services:
      pdns-auth:
        image: "${{ matrix.pdns-auth-image }}"
        ports:
          - "8080:8081"
        env:
          PDNS_AUTH_API_KEY: apipw
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - uses: actions/checkout@v4
      - run: GONOMOCKS=1 go test -v ./...
